import createPlugin from '#utils/createPlugin';

export default () => createPlugin({
    name: 'Test Admin',
    description: 'allows anyone to access the forced admin panel.',
    authors: [{ name: 'Death', avatar: 'https://i.imgur.com/PrvNWub.png', url: 'https://villainsrule.xyz' }],
    patches: [
        {
            file: '/lib/js/game.js',
            replacement: [
                {
                    match: /perm == "none"/,
                    replace: `perm == "none" || page === "Panel"`
                }
            ]
        },
        {
            file: '/lib/js/panel/home.js',
            replacement: [
                {
                    match: /\("\*"\)/,
                    replace: `\("\*"\) || !blacket.panel.buttons[button].disabled`
                }, {
                    match: /"edit_presets"/,
                    replace: `"edit_presets",disabled:true`
                }, {
                    match: /\/\*"/,
                    replace: `"`
                }, {
                    match: /_packs"/,
                    replace: `_packs",disabled:true`
                }, {
                    match: /_reports"/,
                    replace: `_reports",disabled:true`
                }, {
                    match: /\},\*\//,
                    replace: '},'
                }
            ]
        },
        {
            file: '/lib/js/panel/users.js',
            replacement: [
                {
                    match: /let online/,
                    replace: `
                        user.mute = { muted: Math.random() < 0.6 };
                        user.ban = { banned: Math.random() < 0.6 };
                        let online
                    `
                }, {
                    match: /\("ban_users"\)/,
                    replace: `("ban_users") || true`
                }
            ]
        },
        {
            file: '/lib/js/panel/console.js',
            replacement: [
                {
                    match: /\$\("\#commandInputBox"\).k/,
                    replace: `
                        [
                            '[Blacket] Started!',
                            '[Blacket] Type "help" for commands.',
                            '[Blacket] Type "clear" to clear the console.',
                            '[Blacket] Type "exit" to exit the console.',
                            '[Blacket] Please note that this is populated data written by BetterBlacket',
                            '[Blacket] To disable these populations, turn off the TestAdmin plugin.'
                        ].forEach(p => blacket.appendConsoleLine(p));
                        $('#commandInputBox').k`
                }
            ]
        },
        {
            file: '/lib/js/panel/forms.js',
            replacement: [
                {
                    match: /currentPage = 1/,
                    replace: `currentPage = 0`
                },
                {
                    match: /return blacket/,
                    replace: `blacket`
                },
                {
                    match: /maxPages = data\.pages/,
                    replace: `maxPages = 5`
                },
                {
                    match: /blacket\.currentPage = data\.page/,
                    replace: `blacket.currentPage++`
                },
                {
                    match: /data\.forms\.length/,
                    replace: `Math.round(Math.random() * 20)`
                },
                {
                    match: /data\.total/,
                    replace: `Math.round(Math.random() * 70)`
                },
                {
                    match: /data.forms/,
                    replace: `
                        let createAge = () => Math.round(Math.random() * 3) + 13;
                        let createUsername = () => 'Username' + Math.round(Math.random() * 1000);
                        let discord = () => 'username' + Math.round(Math.random() * 1000);
                        let body = () => 'This body was generated by the Test Admin BetterBlacket Plugin. This is NOT a real form. If you are a staff, you can see real forms by disabling this plugin. '.repeat(Math.round(Math.random() * 3));
                    
                        let createForm = () => ({
                            username: createUsername(),
                            age: createAge(),
                            discord: discord(),
                            body: body()
                        });
                    
                        new Array(69).fill().map(() => createForm())`
                }
            ]
        }
    ]
});